# Predict by loading Ling's Model

In [1]:
from tensorflow.keras import layers, models, optimizers, losses, metrics, utils
from tensorflow import keras
from keras.engine import base_layer
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib import image
from datetime import datetime
import os
from PIL import Image

2022-09-01 19:29:26.515548: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-01 19:29:26.517405: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
# Load the saved model
ling = models.load_model(f"../models/VGG16_model_1_Sep")

2022-09-01 19:30:10.667143: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-09-01 19:30:10.668097: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-09-01 19:30:10.669026: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-FIJER02): /proc/driver/nvidia/version does not exist
2022-09-01 19:30:10.680305: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
test_data = utils.image_dataset_from_directory('../raw_data/class_images_min/class_images_min/Test_lemon', seed = 1)

Found 800 files belonging to 2 classes.


In [4]:
predict_ling = ling.predict(test_data)

2022-09-01 19:30:42.368196: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 536870912 exceeds 10% of free system memory.
2022-09-01 19:30:44.459848: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 536870912 exceeds 10% of free system memory.


 1/25 [>.............................] - ETA: 18:24

2022-09-01 19:31:23.930421: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 536870912 exceeds 10% of free system memory.
2022-09-01 19:31:25.150999: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 536870912 exceeds 10% of free system memory.


 2/25 [=>............................] - ETA: 15:09

2022-09-01 19:32:03.427190: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 536870912 exceeds 10% of free system memory.


25/25 [==============================] - 1071s 43s/step


In [7]:
predict_ling

array([[2.17845384e-02],
       [3.00181676e-02],
       [9.99785364e-01],
       [1.14675231e-06],
       [5.87309769e-04],
       [9.99576867e-01],
       [6.32255435e-01],
       [6.63078972e-04],
       [1.41663998e-01],
       [9.99999285e-01],
       [2.42376961e-02],
       [1.49422922e-04],
       [8.76070699e-04],
       [1.00000000e+00],
       [9.99999881e-01],
       [6.65708005e-01],
       [4.42951024e-01],
       [9.82124686e-01],
       [6.01090211e-03],
       [5.06787619e-04],
       [2.42987471e-06],
       [9.87616003e-01],
       [9.99702811e-01],
       [1.36728568e-06],
       [7.46523023e-01],
       [9.99979258e-01],
       [9.99270380e-01],
       [1.00000000e+00],
       [1.66026639e-05],
       [1.00000000e+00],
       [1.56548917e-01],
       [8.36018100e-03],
       [9.74818110e-01],
       [4.60437685e-03],
       [1.00000000e+00],
       [1.00000000e+00],
       [7.01950572e-04],
       [9.98982906e-01],
       [9.98651505e-01],
       [4.24687527e-02],


In [9]:
test_data.__dict__

{'_input_dataset': <ShuffleDataset element_spec=(TensorSpec(shape=(256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>,
 '_batch_size': <tf.Tensor: shape=(), dtype=int64, numpy=32>,
 '_drop_remainder': <tf.Tensor: shape=(), dtype=bool, numpy=False>,
 '_structure': (TensorSpec(shape=(None, 256, 256, 3), dtype=tf.float32, name=None),
  TensorSpec(shape=(None,), dtype=tf.int32, name=None)),
 '_name': None,
 '_variant_tensor_attr': <tf.Tensor: shape=(), dtype=variant, value=<BatchDatasetV2Op(32)::Dataset>>,
 '_graph_attr': <tensorflow.python.framework.ops.Graph at 0x7f1c005d8a90>,
 '_options_attr': <tensorflow.python.data.ops.options.Options at 0x7f1b784d84c0>,
 'class_names': ['Healthy_lemon', 'Unhealthy_lemon'],
 'file_paths': ['../raw_data/class_images_min/class_images_min/Test_lemon/Healthy_lemon/0003_B_H_60_H.jpg',
  '../raw_data/class_images_min/class_images_min/Test_lemon/Unhealthy_lemon/0005_B_H_30_G.jpg',
  '../raw_data/class_images_min/cl

In [12]:
test_data._input_dataset

<ShuffleDataset element_spec=(TensorSpec(shape=(256, 256, 3), dtype=tf.float32, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>